import os
import json
import pandas as pd
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from app.database import get_db
from app.models.datafile import DataFile
from app.routers.data import get_current_user
from app.models.user import User

router = APIRouter(prefix="/reports", tags=["Reports"])


def generate_word_report(db_file, df: pd.DataFrame, current_user: User) -> str:
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Style général
    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(11)

    # En-tête
    header = doc.add_heading('', 0)
    header_run = header.add_run('Data Analysis Report')
    header_run.font.color.rgb = RGBColor(0x6C, 0x63, 0xFF)
    header_run.font.size = Pt(24)
    header.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Ligne de séparation
    doc.add_paragraph('─' * 60)

    # Métadonnées
    meta = doc.add_paragraph()
    meta.add_run('File: ').bold = True
    meta.add_run(db_file.original_filename)
    meta.add_run('\n')
    meta.add_run('Generated: ').bold = True
    meta.add_run(datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
    meta.add_run('\n')
    meta.add_run('Generated by: ').bold = True
    meta.add_run(current_user.username)

    doc.add_paragraph()

    # Résumé statistique
    doc.add_heading('Summary Statistics', level=1)

    summary_data = [
        ('Total Rows', str(len(df))),
        ('Total Columns', str(len(df.columns))),
        ('File Size', f"{db_file.file_size} KB"),
        ('Columns', ', '.join(list(df.columns))),
    ]

    table = doc.add_table(rows=1, cols=2)
    table.style = 'Table Grid'
    hdr = table.rows[0].cells
    hdr[0].text = 'Metric'
    hdr[1].text = 'Value'

    for cell in hdr:
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                run.bold = True

    for metric, value in summary_data:
        row = table.add_row().cells
        row[0].text = metric
        row[1].text = value

    doc.add_paragraph()

    # Statistiques numériques
    numeric_cols = df.select_dtypes(include='number').columns.tolist()
    if numeric_cols:
        doc.add_heading('Numeric Statistics', level=1)
        stats_df = df[numeric_cols].describe().round(2)

        num_table = doc.add_table(rows=1, cols=len(numeric_cols) + 1)
        num_table.style = 'Table Grid'

        header_row = num_table.rows[0].cells
        header_row[0].text = 'Stat'
        for i, col in enumerate(numeric_cols):
            header_row[i + 1].text = col
            for paragraph in header_row[i + 1].paragraphs:
                for run in paragraph.runs:
                    run.bold = True

        for stat_name in stats_df.index:
            row_cells = num_table.add_row().cells
            row_cells[0].text = stat_name
            for i, col in enumerate(numeric_cols):
                row_cells[i + 1].text = str(stats_df.loc[stat_name, col])

        doc.add_paragraph()

    # Tableau de données complet
    doc.add_heading('Data Table', level=1)
    doc.add_paragraph(f'Showing first 50 rows of {len(df)} total rows.')

    preview_df = df.head(50)
    data_table = doc.add_table(rows=1, cols=len(df.columns))
    data_table.style = 'Table Grid'

    header_row = data_table.rows[0].cells
    for i, col in enumerate(df.columns):
        header_row[i].text = str(col)
        for paragraph in header_row[i].paragraphs:
            for run in paragraph.runs:
                run.bold = True

    for _, row in preview_df.iterrows():
        row_cells = data_table.add_row().cells
        for i, col in enumerate(df.columns):
            row_cells[i].text = str(row[col])

    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph('Generated by DataDash — Industrial Data Dashboard')
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in footer.runs:
        run.font.color.rgb = RGBColor(0x94, 0xA3, 0xB8)
        run.font.size = Pt(9)

    output_path = f"/app/uploads/report_{db_file.id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    doc.save(output_path)
    return output_path


def generate_pdf_report(db_file, df: pd.DataFrame, current_user: User) -> str:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.enums import TA_CENTER, TA_LEFT

    output_path = f"/app/uploads/report_{db_file.id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2*cm,
    )

    ACCENT = colors.HexColor('#6C63FF')
    DARK = colors.HexColor('#1e1e2e')
    LIGHT_BG = colors.HexColor('#f8f9fa')
    BORDER = colors.HexColor('#e2e8f0')

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=24,
        textColor=ACCENT,
        spaceAfter=6,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold',
    )
    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#94a3b8'),
        alignment=TA_CENTER,
        spaceAfter=20,
    )
    section_style = ParagraphStyle(
        'Section',
        parent=styles['Heading1'],
        fontSize=14,
        textColor=ACCENT,
        spaceBefore=16,
        spaceAfter=8,
        fontName='Helvetica-Bold',
    )
    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#334155'),
        spaceAfter=4,
    )

    story = []

    # Titre
    story.append(Paragraph("Data Analysis Report", title_style))
    story.append(Paragraph(
        f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')} by {current_user.username}",
        subtitle_style
    ))

    # Ligne séparatrice
    story.append(Table(
        [['']],
        colWidths=[17*cm],
        style=TableStyle([('LINEABOVE', (0,0), (-1,0), 1, ACCENT)])
    ))
    story.append(Spacer(1, 12))

    # Infos fichier
    story.append(Paragraph("File Information", section_style))
    info_data = [
        ['File', db_file.original_filename],
        ['Total Rows', str(len(df))],
        ['Total Columns', str(len(df.columns))],
        ['File Size', f"{db_file.file_size} KB"],
        ['Uploaded', db_file.uploaded_at.strftime('%Y-%m-%d %H:%M')],
    ]
    info_table = Table(info_data, colWidths=[5*cm, 12*cm])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), LIGHT_BG),
        ('TEXTCOLOR', (0, 0), (0, -1), DARK),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.white, LIGHT_BG]),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 16))

    # Statistiques numériques
    numeric_cols = df.select_dtypes(include='number').columns.tolist()
    if numeric_cols:
        story.append(Paragraph("Numeric Statistics", section_style))
        stats_df = df[numeric_cols].describe().round(2)

        stats_header = ['Stat'] + numeric_cols
        stats_data = [stats_header]
        for stat_name in stats_df.index:
            row = [stat_name] + [str(stats_df.loc[stat_name, col]) for col in numeric_cols]
            stats_data.append(row)

        col_width = 17*cm / len(stats_header)
        stats_table = Table(stats_data, colWidths=[col_width]*len(stats_header))
        stats_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('ALIGN', (1, 1), (-1, -1), 'CENTER'),
        ]))
        story.append(stats_table)
        story.append(Spacer(1, 16))

    # Tableau de données
    story.append(Paragraph("Data Preview (first 50 rows)", section_style))
    story.append(Paragraph(
        f"Showing {min(50, len(df))} of {len(df)} rows.",
        body_style
    ))

    preview_df = df.head(50).fillna('')
    table_data = [list(df.columns)]
    for _, row in preview_df.iterrows():
        table_data.append([str(v)[:20] for v in row.values])

    col_w = 17*cm / len(df.columns)
    data_table = Table(table_data, colWidths=[col_w]*len(df.columns))
    data_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ('PADDING', (0, 0), (-1, -1), 5),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
    ]))
    story.append(data_table)

    # Footer
    story.append(Spacer(1, 20))
    story.append(Table(
        [['']],
        colWidths=[17*cm],
        style=TableStyle([('LINEABOVE', (0,0), (-1,0), 0.5, BORDER)])
    ))
    story.append(Paragraph(
        "Generated by DataDash — Industrial Data Dashboard",
        subtitle_style
    ))

    doc.build(story)
    return output_path


@router.post("/generate/{file_id}")
async def generate_report(
    file_id: int,
    format: str = "pdf",
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    db_file = db.query(DataFile).filter(
        DataFile.id == file_id,
        DataFile.user_id == current_user.id
    ).first()

    if not db_file:
        raise HTTPException(status_code=404, detail="File not found")

    try:
        if db_file.original_filename.endswith('.csv'):
            df = pd.read_csv(db_file.file_path)
        else:
            df = pd.read_excel(db_file.file_path)
        df = df.fillna('')
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Could not read file: {str(e)}")

    try:
        if format == "word":
            output_path = generate_word_report(db_file, df, current_user)
            media_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            filename = f"report_{db_file.original_filename.replace('.csv','').replace('.xlsx','')}.docx"
        else:
            output_path = generate_pdf_report(db_file, df, current_user)
            media_type = "application/pdf"
            filename = f"report_{db_file.original_filename.replace('.csv','').replace('.xlsx','')}.pdf"

        return FileResponse(
            path=output_path,
            media_type=media_type,
            filename=filename,
            background=None
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Report generation failed: {str(e)}")